---

- name: Write out Ansible hosts config
  copy:
    content: >
      {{ openshift_ansible_inventory
      |to_nice_yaml|regex_replace('<host-inserted-here>', inventory_hostname) }}
    dest: /etc/ansible/hosts

- name: k8s templated objects directory
  file:
    state: directory
    path: "{{ openshift_ansible_tmp }}"

- name: Generate SSH key
  command: ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N ""
  args:
    creates: /root/.ssh/id_rsa

- name: Retrieve SSH public key
  slurp:
    src: /root/.ssh/id_rsa.pub
  register: ansible_public_key_slurp

- name: Save SSH public key to fact
  set_fact:
    public_key: "{{ ansible_public_key_slurp.content | b64decode }}"

- name: Create group of Ansible hosts
  group_by:
    key: openshift_ansible_hosts
