---

- block:
  - import_tasks: dependencies.yml
  - import_tasks: ansible-dir.yml
  - import_tasks: ansible.yml
    # TODO: run Ansible deployment on the host and wait for it to complete
  when: openshift_is_ansible_host

- import_tasks: node.yml

- block:
  - import_tasks: ansible-dir.yml
  - import_tasks: users.yml
  - import_tasks: localstorage-master.yml
    when: openshift_localstorage_hosts
  when: openshift_is_master_host

- import_tasks: localstorage-dirs.yml
  when: openshift_localstorage_enabled

